sonar.projectKey=promap
sonar.projectName=ProMaP
sonar.sources=app,components,hooks,lib,middleware.ts,scripts,prisma
sonar.exclusions=node_modules/**,.next/**,.scannerwork/**,coverage/**,public/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_de524fa6b3697fecb83e6c14830aee029e4cfe49
